braille = dict()
braille[1] = 0
braille[2] = 16
braille[3] = 32
braille[4] = 2
braille[5] = 18
braille[6] = 34
cells = dict()
cells["a"] = [braille[1]] #
cells["b"] = [braille[1], braille[2]]
cells["c"] = [braille[1], braille[4]]
cells["d"] = [braille[1], braille[4], braille[5]]
cells["e"] = [braille[1], braille[5]]
cells["f"] = [braille[1], braille[2], braille[4]]
cells["g"] = [braille[1], braille[2]]
cells["g"] = [braille[1], braille[2], braille[4], braille[5]]
cells["h"] = [braille[1], braille[2], braille[5]]
cells["i"] = [braille[2], braille[4]]
cells["j"] = [braille[2], braille[4], braille[5]]
cells["k"] = [braille[1], braille[3]]
cells["l"] = [braille[1], braille[2], braille[3]]
cells["m"] = [braille[1], braille[3], braille[4]]
cells["n"] = [braille[1], braille[3], braille[4], braille[5]]
cells["o"] = [braille[1], braille[3], braille[5]]
cells["p"] = [braille[1], braille[2], braille[3], braille[4]]
cells["q"] = [braille[1], braille[2], braille[3], braille[4], braille[5]]
cells["r"] = [braille[1], braille[2], braille[3], braille[5]]
cells["s"] = [braille[2], braille[3], braille[4]]
cells["t"] = [braille[2], braille[3], braille[4], braille[5]]
cells["u"] = [braille[1], braille[3], braille[6]]
cells["v"] = [braille[1], braille[2], braille[3], braille[6]]
cells["w"] = [braille[2], braille[4], braille[5], braille[6]]
cells["x"]  [braille[1], braille[3], braille[4], braille[6]]
cells["y"] = [braille[1], braille[3], braille[4], braille[5], braille[6]]
cells["z"] = [braille[1], braille[3], braille[5], braille[6]]